[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pynvim>=0.5.2",
    "pyright>=1.1.395",
    "python-language-server>=0.36.2",
]
