apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: example
spec:
  containers:
  - name: web
    image: nginx:latest
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      value: "development"
